// src/pages/index.ts
export {Home} from './home';
export {Dashboard} from './dashboard';
export {Specialities} from './specialities';
export {DoctorsList} from './doctor-list';
export {DoctorSlotSelection} from './doctor-slots-selection';
export {SlotConfirmation} from './slot-confirmation';
export {default as BookVaccination} from './BookVaccination';
export {default as VaccinesAdult} from './VaccinesAdult';
export {default as BookScan} from './BookScan';
export {default as MedicalRecord} from './MedicalRecord';
export {default as MyAppointments} from './appointments/appointment-list';
export {PayUWebView} from './slot-confirmation';
export {default as MyAppointmentDetails} from './appointments/appointment-details';
export {default as VaccinesPediatric} from './VaccinesPediatric';
export {default as AppointmentConfirmed} from './appointments/appointment-confirmation';
export {default as AppointmentChat} from './appointments/appointment-chat';
export {Login} from './login';
export {Otp} from './otp';
export {default as Registration} from './Registration';
